---
swagger: "2.0"
info:
  description: QuarterKings is an API which allows game developers to easily implement arcade type leaderboards without the hassle of making their own database.
  version: 1
  title: QuarterKings API
  contact:
    email: pocketPrince@quarterKings.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: sean-green-cst.com
basePath: /quarterKings/v1
tags:
- name: admin
  description: Completed admin endpoints
- name: developer
  description: Completed developer endpoints
- name: planned
  description: Planned operations available to regular developers
schemes:
- https
paths:
  /signup:
    post:
      tags:
      - admin
      summary: Create new User entry and login
      description: Creates a user in the users table of the database
      parameters: 
      - name: name
        in: body
        description: user name to be created
        type: string
      - name: password
        in: body
        description: user password to be created
        type: string
      responses:
        "201":
          description: account created
        "400":
          description: invalid input, object invalid
        "403":
          description: request forbidden by origin header
        "409":
          description: an existing item already exists
  /login:
    post:
      tags:
      - admin
      summary: Confirm user exists in system
      description: Checks the user name and password against the database entry
      parameters: 
      - name: name
        in: body
        description: user name to be queried
        type: string
      - name: password
        in: body
        description: user password to be queried
        type: string
      responses:
        "200":
          description: credentials confirmed
        "400":
          description: invalid object sent to server
        "401":
          description: invalid username or password
        "403":
          description: request forbidden by origin header
        "500":
          description: error description returned with status
  /generate:
    post:
      tags:
      - admin
      summary: generates and returns a new API key for the user
      description: Generates a random 16 character string for the user to use as an API key to store scores in our database.
      parameters: 
      - name: name
        in: body
        description: user name to be confirmed
        type: string
      - name: password
        in: body
        description: user password to be confirmed
        type: string
      - name: domain
        in: body
        type: string
        description: host url of app that will use this api-key
      responses:
        "201":
          description: returns a json object with the newly created api key
        "400":
          description: invalid object sent to server
        "401":
          description: invalid username or password
        "403":
          description: request forbidden by origin header
  /getKeys:
    post:
      tags:
      - admin
      summary: get a list of keys connected to the provided user
      description: Returns a list of keys connected to the provided user
      parameters:
      - name: name
        in: body
        description: username or email of account
        required: true
        type: string
      - name: password
        in: body
        description: password attached to account name
        required: true
        type: string
      responses:
        "200":
          description: returns an array of apikey/domain objects
        "400":
          description: invalid input/object
        "401":
          description: invalid username or password
        "403":
          description: request forbidden by origin header
  /score:
    post:
      tags:
      - developer
      summary: Create new entry in score table
      description: Insert a score into the database attached to the API key provided
      parameters: 
      - name: name
        in: body
        description: player name
        required: true
        type: string
      - name: score
        in: body
        description: player score
        required: true
        type: float
      - name: apiKey
        in: body
        description: apiKey to store the score under
        required: true
        type: string
      responses:
        "201":
          description: Success
        "400":
          description: Invalid object
        "401":
          description: apiKey invalid
  /stats:
    post:
      tags:
        - admin
      summary: Get the stats on how many times each endpoint has been hit semi successfully
      description: takes a special admin name and password and returns the hits of each endpoint in the api as an array
      parameters: 
      - name: name
        in: body
        description: admin account name
        required: true
        type: string
      - name: password
        in: body
        description: password attached to account name
        required: true
        type: string
      responses:
        "200":
          description: returns and array of stat objects
        "400":
          description: Invalid object
        "401":
          description: apiKey invalid
        "403":
          description: forbidden
  /getScores:
    get:
      tags:
      - developer
      summary: Get a list of scores connected to the provided api key
      description: Returns a list of scores based on the api key attached to query
      parameters:
      - name: api
        in: query
        description: The API key connected to the scores you wish to access
        required: true
        type: string
      responses:
        "200":
          description: returns an array of score objects
        "400":
          description: no api key provided
        "500":
          description: internal server error
  /deleteAll:
    delete:
      tags:
      - developer
      summary: Delete all scores associated with an apiKey
      description: TODO FILL THIS IN
      parameters: 
      - name: apiKey
        in: body
        description: The API key connected to the scores you wish to delete
        required: true
        type: string
      responses:
        "204":
          description: Success
        "400":
          description: Invalid Object
  /deleteScore:
    delete:
      tags:
      - developer
      summary: Delete a single entry from the score table
      description: Send the api key and id of the score in the body and QuarterKings will delete the corresponding entry
      parameters: 
      - name: apiKey
        in: body
        description: The API key connected to the score you wish to delete
        required: true
        type: string
      - name: id
        in: body
        description: The id connected to the score you wish to delete
        required: true
        type: integer
      responses:
        "204":
          description: OK
        "400":
          description: Invalid Object  
  /deleteApiKey:
    delete:
      tags:
      - admin
      summary: Delete an api key and all scores attached to it
      description: Delete an api key and all scores attached to it
      parameters: 
      - name: apiKey
        in: body
        description: The API key connected to the score you wish to delete
        required: true
        type: string
      - name: name
        in: body
        description: user account name
        required: true
        type: string
      - name: password
        in: body
        description: user account password
        required: true
        type: string
      responses:
        "204":
          description: OK
        "400":
          description: Invalid Object
  /updateDomain:
    put:
      tags:
      - developer
      summary: Update the domain name at the given api key
      description: TODO FILL THIS IN
      parameters: 
      - name: apiKey
        in: body
        description: The API key whos domain you want to update
        required: true
        type: string
      - name: name
        in: body
        description: Username of user who wants to update a domain
        required: true
        type: string
      - name: password
        in: body
        description: The password connected to the score you wish to delete
        required: true
        type: string
      - name: domain
        in: body
        description: The domain connected to the score you wish to delete minus the https://
        required: true
        type: string
      responses:
        "204":
          description: Success
        "400":
          description: Invalid Object
        "500":
          description: Internal server error
  /updateScore:
    put:
      tags:
      - developer
      summary: update the score 
      description: TODO FILL THIS IN
      parameters: 
      - name: apiKey
        in: body
        description: The API key whos score you want to update
        required: true
        type: string 
      - name: id
        in: body
        description: The score id whos score you want to update
        required: true
        type: int
      - name: score
        in: body
        description: The new score 
        required: true
        type: float
      responses:
        "204":
          description: Success
        "400":
          description: Invalid Object
        "500":
          description: Internal server error