---
swagger: "2.0"
info:
  description: QuarterKings is an API which allows game developers to easily implement arcade type leaderboards without the hassle of making their own database.
  version: 1
  title: QuarterKings API
  contact:
    email: pocketPrince@quarterKings.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: sean-green-cst.com
basePath: /quarterKings/v1
tags:
- name: admin complete
  description: Completed admin endpoints
- name: developers complete
  description: Completed developer endpoints
- name: planned
  description: Planned operations available to regular developers
schemes:
- https
paths:
  /signup:
    post:
      tags:
      - admin complete
      summary: Create new User entry and login
      description: Creates a user in the users table of the database
      parameters: 
      - name: name
        in: body
        description: user name to be created
        type: string
      - name: password
        in: body
        description: user password to be created
        type: string
      responses:
        "201":
          description: account created
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
  /login:
    post:
      tags:
      - admin complete
      summary: Confirm user exists in system and return 200
      description: Checks the user name and password against the database entry
      parameters: 
      - name: name
        in: body
        description: user name to be queried
        type: string
      - name: password
        in: body
        description: user password to be queried
        type: string
      responses:
        "200":
          description: credentials confirmed
        "400":
          description: invalid object sent to server
        "404":
          description: invalid username or password
        "500":
          description: error description returned with status
  /generate:
    post:
      tags:
      - admin complete
      summary: generates and returns a new API key for the user
      description: Generates a random 16 character string for the user to use as an API key to store scores in our database.
      parameters: 
      - name: name
        in: body
        description: user name to be confirmed
        type: string
      - name: password
        in: body
        description: user password to be confirmed
        type: string
      - name: domain
        in: body
        type: string
        description: host url of app that will use this api-key
      responses:
        "201":
          description: returns a json object with the newly created api key
        "400":
          description: invalid object sent to server
        "404":
          description: invalid username or password
        "500":
          description: error description returned with status
  /score:
    post:
      tags:
      - planned
      summary: Create new entry in score table
      description: TODO FILL THIS IN
      parameters: []
      responses:
        "200":
          description: OK
  /deleteAll:
    delete:
      tags:
      - planned
      summary: Delete an API key and all scores associated with it.
      description: TODO FILL THIS IN
      parameters: []
      responses:
        "200":
          description: OK
  /deleteScore:
    delete:
      tags:
      - planned
      summary: Delete a single entry from the score table
      description: TODO FILL THIS IN
      parameters: []
      responses:
        "200":
          description: OK
  /updateDomain:
    put:
      tags:
      - planned
      summary: Update the domain name at the given api key
      description: TODO FILL THIS IN
      parameters: []
      responses:
        "200":
          description: OK
  /updateEmail:
    put:
      tags:
      - planned
      summary: Update the users login email
      description: TODO FILL THIS IN
      parameters: []
      responses:
        "200":
          description: OK
  /getScores:
    get:
      tags:
      - developers complete
      summary: Get a list of scores connected to the provided api key
      description: Returns a list of scores based on the api key attached to query
      parameters:
      - name: api
        in: query
        description: The API key connected to the scores you wish to access
        required: true
        type: string
      responses:
        "200":
          description: OK
  /inventory:
    get:
      tags:
      - planned
      summary: searches inventory
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      operationId: searchInventory
      produces:
      - application/json
      parameters:
      - name: searchString
        in: query
        description: pass an optional search string for looking up inventory
        required: false
        type: string
      - name: skip
        in: query
        description: number of records to skip for pagination
        required: false
        type: integer
        minimum: 0
        format: int32
      - name: limit
        in: query
        description: maximum number of records to return
        required: false
        type: integer
        maximum: 50
        minimum: 0
        format: int32
      responses:
        "200":
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/InventoryItem'
        "400":
          description: bad input parameter
    post:
      tags:
      - admins
      summary: adds an inventory item
      description: Adds an item to the system
      operationId: addInventory
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: inventoryItem
        description: Inventory item to add
        required: false
        schema:
          $ref: '#/definitions/InventoryItem'
      responses:
        "201":
          description: item created
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
definitions:
  InventoryItem:
    type: object
    required:
    - id
    - manufacturer
    - name
    - releaseDate
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      name:
        type: string
        example: Widget Adapter
      releaseDate:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001+0000
      manufacturer:
        $ref: '#/definitions/Manufacturer'
  Manufacturer:
    required:
    - name
    properties:
      name:
        type: string
        example: ACME Corporation
      homePage:
        type: string
        format: url
        example: https://www.acme-corp.com
      phone:
        type: string
        example: 408-867-5309
